# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":lambda"
    replace: "λ"

  - trigger: ":alpha"
    replace: "α"

  - trigger: ":->"
    replace: "→"

  - trigger: ":ss"
    replace: "ß"

  - trigger: ":ae"
    replace: "ä"

  - trigger: ":oe"
    replace: "ö"

  - trigger: ":ue"
    replace: "ü"

  - trigger: ":Ss"
    replace: "ẞ"

  - trigger: ":Ae"
    replace: "Ä"

  - trigger: ":Oe"
    replace: "Ö"

  - trigger: ":Ue"
    replace: "Ü"
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
