#!/bin/sh
alias vim="nvim"
#alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"
alias sudo="sudo "
alias ref="shortcuts >/dev/null; source ~/.config/shortcutrc"


# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias surf="surf -N"
alias ip="ip -color"
alias pacman="pacman --color=auto"
alias yay="yay --color=auto"

