#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	magit="nvim -c MagitOnly" \
	trem="transmission-remote" 				\
	x="sxiv -ft *" 						\
	sudo="sudo "						\
	ls="ls -hN --color=auto --group-directories-first" 	\
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	ffmpeg="ffmpeg -hide_banner"				\
	ls="ls -hN --color=auto --group-directories-first"	\
	grep="grep --color=auto"				\
	diff="diff --color=auto"				\
	ccat="highlight --out-format=ansi"			\
	surf="surf -N"						\
	ip="ip -color"						\
	pacman="pacman --color=auto"				\
	yay="yay --color=auto"					\
	gitr="git --git-dir=$HOME/.git-rice"			\
	gitp="git --git-dir=$HOME/.git-personal"


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
